create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_type text not null,
  page_key text not null,
  user_id uuid not null references public.users(id) on delete cascade,
  user_name text not null,
  content text not null,
  created_at text not null
);

alter table public.comments add column if not exists user_id uuid;
alter table public.comments add column if not exists user_name text;
alter table public.users drop column if exists avatar_seed;
alter table public.comments drop column if exists avatar_seed;

create index if not exists comments_page_idx
on public.comments (page_type, page_key, id desc);

create index if not exists comments_user_idx
on public.comments (user_id, id desc);
