-- RAG 向量库（pgvector）初始化脚本
-- 默认使用 embedding-3 的 1024 维。
-- 如果你改成其他维度，需要同时修改:
-- 1) 本文件中的 vector(1024)
-- 2) .env 里的 RAG_EMBEDDING_DIM

create extension if not exists vector;

create table if not exists public.rag_chunks (
  id bigint generated by default as identity primary key,
  chunk_uid text not null unique,
  source text not null,
  link text not null,
  source_type text not null default 'general',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1024) not null,
  updated_at timestamptz not null default now()
);

create index if not exists rag_chunks_source_idx
on public.rag_chunks (source_type, updated_at desc);

create index if not exists rag_chunks_embedding_idx
on public.rag_chunks using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create or replace function public.upsert_rag_chunks(payload jsonb)
returns integer
language plpgsql
as $$
declare
  item jsonb;
  affected integer := 0;
begin
  if jsonb_typeof(payload) is distinct from 'array' then
    raise exception 'payload must be a json array';
  end if;

  for item in select value from jsonb_array_elements(payload) as value loop
    insert into public.rag_chunks (
      chunk_uid,
      source,
      link,
      source_type,
      content,
      metadata,
      embedding,
      updated_at
    )
    values (
      item->>'chunk_uid',
      coalesce(item->>'source', '未知来源'),
      coalesce(item->>'link', '/assistant'),
      coalesce(item->>'source_type', 'general'),
      coalesce(item->>'content', ''),
      coalesce(item->'metadata', '{}'::jsonb),
      (item->>'embedding')::vector(1024),
      now()
    )
    on conflict (chunk_uid) do update set
      source = excluded.source,
      link = excluded.link,
      source_type = excluded.source_type,
      content = excluded.content,
      metadata = excluded.metadata,
      embedding = excluded.embedding,
      updated_at = now();

    affected := affected + 1;
  end loop;

  return affected;
end;
$$;

create or replace function public.match_rag_chunks(
  query_embedding vector(1024),
  match_count integer default 4,
  min_similarity double precision default 0.45
)
returns table (
  chunk_uid text,
  source text,
  link text,
  source_type text,
  content text,
  similarity double precision
)
language sql
stable
as $$
  select
    c.chunk_uid,
    c.source,
    c.link,
    c.source_type,
    c.content,
    1 - (c.embedding <=> query_embedding) as similarity
  from public.rag_chunks as c
  where (1 - (c.embedding <=> query_embedding)) >= min_similarity
  order by c.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;
