create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_type text not null,
  page_key text not null,
  user_name text not null,
  avatar_seed text not null,
  content text not null,
  created_at text not null
);

create index if not exists comments_page_idx
on public.comments (page_type, page_key, id desc);
